blueprint:
  name: Budík
  description: Po zazvonění budíku v mobilu a splněných podmínkách spustí akci
  domain: automation
  author: m
  source_url: https://github.com/Loriet/HA/blob/main/3.yaml

  input:
    mobil_budik:
      name: Budík mobilu
      description: Vyber zařízení s budíkem
      selector:
        entity:
          integration: mobile_app
          device_class: timestamp
          multiple: false
    slunce:
      name: Slunce 
      description: Běží jen po západu slunce NE/ANO
      default: false
      selector:
        boolean:
    lide:
      name: Lidé
      description: Vyber osobu 
      selector:
        entity:
          integration: person
          multiple: false
    lokace:
      name: Lokace
      description: Vyberte lokaci kde se má osoba nacházet
      selector:
        entity:
          integration: zone
          multiple: false
    akce:
      name: Akce 
      description: Vyber zařízení, které má být spuštěno
      default: []
      selector:
        action: {}
variables:
  slunce: !input slunce
trigger:
  - platform: time
    at: !input mobil_budik
condition:
  - condition: template
    value_template: "{{ slunce == false }}"
  - condition: sun
    before: sunrise
    before: sunset
  - condition: zone
    entity_id: !input lide
    zone: !input lokace
action: !input akce  
mode: single


    




