blueprint:
  name: Budík
  description: Po zazvonění budíku v mobilu a splněných podmínkách spustí akci
  domain: automation
  author: m
  source_url: https://github.com/Loriet/HA/blob/main/3.yaml

  input:
    budik_pomocnik:
      name: Pomocník 
      description: Vyber pomocníka pro datum a čas
      selector:
        entity:
          integration: input_datetime
          multiple: false
    mobil_budik:
      name: Budík mobilu
      description: Vyber zařízení s budíkem
      selector:
        entity:
          integration: mobile_app
          device_class: timestamp
          multiple: false
    slunce:
      name: Slunce 
      description: Běží pouze v noci (mezi západem a východem slunce)
      default: false
      selector:
        boolean:
    lide:
      name: Lidé
      description: Vyber kdo má být doma 
      selector:
        entity:
          integration: person
          multiple: false
    lokace:
      name: Lokace
      description: Vyberte lokaci kde se má osoba nacházet
      selector:
        entity:
          integration: zone
          multiple: false
    akce:
      name: Akce 
      description: Vyber zařízení, které má být spuštěno
      default: []
      selector:
        action: {}
variables:
  slunce: !input slunce
trigger:
  - platform: time
    at: !input budik_pomocnik
    id: pockej
  - platform: state
    entity_id: !input mobil_budik
condition:
  - condition: trigger
    id: pockej
  - condition: template
    value_template: "{{ slunce == false }}"
  - condition: sun
    before: sunrise
    before: sunset
  - condition: state
    entity_id: !input lide
    state: !input lokace
action: !input akce
mode: single


    




